CREATE SEQUENCE IF NOT EXISTS virtual_service_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS virtual_service (id INTEGER GENERATED BY DEFAULT AS SEQUENCE virtual_service_seq PRIMARY KEY,
    operationid varchar(250), input longvarchar(25000),url varchar(250),method varchar(50), type varchar(50),priority INTEGER,
    output longvarchar(25000), resources varchar(250), httpStatusCode varchar(250),rule varchar(2500),
    excludeList varchar(250), availableParamsList varchar(2500), headerParamsList varchar(2500),
    lastUsedDateTime TIMESTAMP, usageCount INTEGER);

